services:
  postgres_sae_tt:
    build:
      context: .
      dockerfile: Dockerfile.postgis-pgvector
    environment:
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: esferico_sae_tt_db
    ports:
      - "5432:5432"
    volumes:
      - ./init-extensions.sql:/docker-entrypoint-initdb.d/init-extensions.sql:ro
      - pgdata_sae_tt:/var/lib/postgresql

  postgres_sae_tt_tests:
    build:
      context: .
      dockerfile: Dockerfile.postgis-pgvector
    environment:
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: esferico_sae_tt_tests_db
    ports:
      - "5433:5432"
    volumes:
      - ./init-extensions.sql:/docker-entrypoint-initdb.d/init-extensions.sql:ro
      - pgdata_sae_tt_tests:/var/lib/postgresql

volumes:
  pgdata_sae_tt:
  pgdata_sae_tt_tests: